# Generated by Django 5.2.3 on 2025-06-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.cidade'),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
